name: CI workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types: [user-service-pr]

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      # Step 1: Clone the code from the repository
      - name: Clone production repo
        run: |
          git clone https://github.com/Null-By-Design/user-service.git
          
      # Step 2: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Set up Python environment
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      # Step 4: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev gcc

      # Step 5: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run tests
      - name:  Lint with flake8
        run: |
         pip install --upgrade flake8
         flake8 src/api --count --select=* --show-source --statistics --max-line-length=135

      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest --maxfail=5  

      - name: Check Coverage
        run: |
          pip install pytest-cov
          pytest --cov=src/api --cov-report=term 
        env:
          CI: true 
          
